CompanyName: FeelUOwn
FileDescription: FeelUOwn
InternalName: FeelUOwn
LegalCopyright: © FeelUOwn. All rights reserved.
OriginalFilename: FeelUOwn.exe
ProductName: FeelUOwn
Translation:
  - langID: 2052
    charsetID: 1200
