name: Release for macos
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-n-publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5
        pip install pyinstaller
        pip install -e .[macos,battery]
    - name: Install libmpv
      run: |
        brew install mpv
    - name: Bundle
      run: |
        make bundle
    - name: Archive
      run: |
        # List dist to help double check if bundle is ok.
        ls dist/
        cd dist/ && zip FeelUOwnX.zip -r FeelUOwnX.app/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: FeelUOwnX.zip
        path: dist/FeelUOwnX.zip
    - name: Upload to release page
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/FeelUOwnX.zip
