name: Release for macos
on:
  push:
    tags:
      - v*
    branches:
      - master
  workflow_dispatch:

jobs:
  build-n-publish:

    runs-on: ${{ matrix.os }}
    strategy:
      # Allow some jobs fail.
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13, macos-12]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5
        pip install pyinstaller
        pip install -e .[macos,battery,cookies,ytdl]
    - name: Install libmpv
      run: |
        brew install mpv
    - name: Bundle
      run: |
        make bundle
    - name: Archive
      run: |
        # List dist to help double check if bundle is ok.
        ls dist/
        arch=`uname -m`
        macos_version=`sw_vers -productVersion`
        echo "DIST_ARCH=${arch}" >> $GITHUB_ENV
        echo "DIST_MACOS_VERSION=${macos_version}" >> $GITHUB_ENV
        cd dist/ && zip FeelUOwnX-macOS${macos_version}-${arch}.zip -r FeelUOwnX.app/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: FeelUOwnX-macOS{{ env.DIST_MACOS_VERSION }}-{{ env.DIST_ARCH }.zip
        path: dist/FeelUOwnX-macOS{{ env.DIST_MACOS_VERSION }}-{{ env.DIST_ARCH }.zip
    - name: Upload to release page
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/FeelUOwnX-macOS{{ env.DIST_MACOS_VERSION }}-{{ env.DIST_ARCH }.zip
    - name: Upload to nightly
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/FeelUOwnX-macOS{{ env.DIST_MACOS_VERSION }}-{{ env.DIST_ARCH }.zip
        tag_name: nightly
