name: telegram message
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on pull request opened
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.FEELUOWN_TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            新 PR 来辽，一起去评审它吧！
            ${{ github.event.pull_request.html_url }}
